version: '2'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  mongodb:
    image: "mongo"
  sch:
    build: .
    image: cta-oss/cta-app-schedulerdataservice:compose
    ports:
      - "3011:3011"
    depends_on: 
      - rabbitmq
      - mongodb

